services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
      - ./app/data/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db     
  
  app:
    build: "app/."
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - userdata:/root
      - ./app/Codebase:/var/www/html
    links:
      - adminer
      - db
  
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  userdata:
  db_data:
  mongo_data:
